codecov:
  notify:
    after_n_builds: 2
    wait_for_ci: false

  require_ci_to_pass: false
  token: 74bc381b-9c5f-44c1-9efa-af57d5f3fe50  # notsecret  # repo-scoped, upload-only, stability in fork PRs

coverage:
  range: 40..100
  status:
    project:
      default:
        target: 60%
        threshold: 10%
      app:
        target: 60%
        threshold: 10%
        paths:
          - src/
      tests:
        target: 100%
        paths:
          - tests/

    patch:
      default:
        target: 100%
        threshold: 10%
      app:
        target: 100%
        threshold: 10%
        paths:
          - src/
      tests:
        target: 100%
        paths:
          - tests/
