apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linux-mcp-logs
  namespace: rhel-mcp
  labels:
    app: linux-mcp-server
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # Optional: Specify storage class
  # storageClassName: gp3-csi
  volumeMode: Filesystem

