apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: pipeline-build-multiarch

spec:
  params:
    - name: git-url
      description: Source Repository URL
      type: string

    - name: revision
      description: Revision of the Source Repository
      type: string
      default: ""

    - name: output-image
      description: Fully Qualified Output Image
      type: string

    - name: build-platforms
      description: List of platforms to build the container images on. The available set of values is determined by the configuration of the multi-platform-controller.
      type: array
      default:
        - linux/arm64
        - linux/amd64

    - name: path-context
      description: Path to the source code of an application's component from where to build image.
      type: string
      default: .

    - name: dockerfile
      description: Path to the Dockerfile inside the context specified by parameter path-context
      type: string
      default: Dockerfile

    - name: rebuild
      description: Force rebuild image
      type: string
      default: "false"

    - name: skip-checks
      description: Skip checks against built image
      type: string
      default: "false"

    - name: hermetic
      description: Execute the build with network isolation
      type: string
      default: "false"

    - name: prefetch-input
      description: Build dependencies to be prefetched by Cachi2
      type: string
      default: ""

    - name: image-expires-after
      description: Image tag expiration time, time values could be something like 1h, 2d, 3w for hours, days, and weeks, respectively.
      default: ""

    - name: build-image-index
      description: Add built image into an OCI image index
      default: "true"

    - name: buildah-format
      description: The format for the resulting image's mediaType. Valid values are oci or docker.
      default: docker
      type: string

    - name: build-args
      description: Array of --build-arg values ("arg=value" strings) for buildah
      type: array
      default: []

    - name: build-args-file
      description: Path to a file with build arguments for buildah, see https://www.mankier.com/1/buildah-build#--build-arg-file
      type: string
      default: ""

    - name: privileged-nested
      description: Whether to enable privileged mode, should be used only with remote VMs
      default: "false"
      type: string

    - name: tag-prefix
      description: Prefix added to additional tags
      type: string
      default: ""

    - name: additional-tags
      description: Additional tags to apply to the image
      type: array
      default: []

  results:
    - name: IMAGE_URL
      description: ""
      value: $(tasks.build-image-index.results.IMAGE_URL)

    - name: IMAGE_DIGEST
      description: ""
      value: $(tasks.build-image-index.results.IMAGE_DIGEST)

    - name: CHAINS-GIT_URL
      description: ""
      value: $(tasks.clone-repository.results.url)

    - name: CHAINS-GIT_COMMIT
      description: ""
      value: $(tasks.clone-repository.results.commit)

  tasks:
    - name: init
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: init

          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-init:0.3@sha256:aa6f8632cc23d605c5942505ff1d00280db16a6fda5c4c56c4ed9ae936b5fbc6

          - name: kind
            value: task

    - name: clone-repository
      params:
        - name: url
          value: $(params.git-url)

        - name: revision
          value: $(params.revision)

        - name: ociStorage
          value: $(params.output-image).git

        - name: ociArtifactExpiresAfter
          value: $(params.image-expires-after)

        - name: fetchTags
          value: "true"

        - name: depth
          value: 42

      runAfter:
        - init

      taskRef:
        resolver: bundles
        params:
          - name: name
            value: git-clone-oci-ta

          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-git-clone-oci-ta:0.1@sha256:306b69e6db435ad4a7cf258b6219d9b998eb37da44f5e9ac882ac86a08109154

          - name: kind
            value: task

      workspaces:
        - name: basic-auth
          workspace: git-auth

    - name: prefetch-dependencies
      params:
        - name: input
          value: $(params.prefetch-input)

        - name: SOURCE_ARTIFACT
          value: $(tasks.clone-repository.results.SOURCE_ARTIFACT)

        - name: ociStorage
          value: $(params.output-image).prefetch

        - name: ociArtifactExpiresAfter
          value: $(params.image-expires-after)

      runAfter:
        - clone-repository

      taskRef:
        resolver: bundles
        params:
          - name: name
            value: prefetch-dependencies-oci-ta

          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-prefetch-dependencies-oci-ta:0.2@sha256:c07551efbd7fc414ae1245ddd93579b00317fee0734980f539fd8aea3cfcb945

          - name: kind
            value: task

      workspaces:
        - name: git-basic-auth
          workspace: git-auth

        - name: netrc
          workspace: netrc

    - name: get-version
      params:
        - name: source_artifact
          value: $(tasks.clone-repository.results.SOURCE_ARTIFACT)

      runAfter:
        - clone-repository

      taskRef:
        name: get-version

    - name: build-images
      matrix:
        params:
          - name: PLATFORM
            value:
              - $(params.build-platforms)

      params:
        - name: IMAGE
          value: $(params.output-image)

        - name: DOCKERFILE
          value: $(params.dockerfile)

        - name: CONTEXT
          value: $(params.path-context)

        - name: HERMETIC
          value: $(params.hermetic)

        - name: PREFETCH_INPUT
          value: $(params.prefetch-input)

        - name: IMAGE_EXPIRES_AFTER
          value: $(params.image-expires-after)

        - name: COMMIT_SHA
          value: $(tasks.clone-repository.results.commit)

        - name: BUILD_ARGS
          value:
            - $(params.build-args[*])
            - PSEUDO_VERSION=$(tasks.get-version.results.pseudo_version)
            - VERSION=$(tasks.get-version.results.version)

        - name: BUILD_ARGS_FILE
          value: $(params.build-args-file)

        - name: PRIVILEGED_NESTED
          value: $(params.privileged-nested)

        - name: SOURCE_URL
          value: $(tasks.clone-repository.results.url)

        - name: BUILDAH_FORMAT
          value: $(params.buildah-format)

        - name: SOURCE_ARTIFACT
          value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)

        - name: CACHI2_ARTIFACT
          value: $(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)

        - name: IMAGE_APPEND_PLATFORM
          value: "true"

      runAfter:
        - get-version

      taskRef:
        params:
          - name: name
            value: buildah-remote-oci-ta

          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-buildah-remote-oci-ta:0.8@sha256:4c6e3e4c3fe8a289161dfbc38a162d28a0289eb4d51f835e847f8c3677a211f3

          - name: kind
            value: task

        resolver: bundles

    - name: build-image-index
      params:
        - name: IMAGE
          value: $(params.output-image)

        - name: COMMIT_SHA
          value: $(tasks.clone-repository.results.commit)

        - name: IMAGE_EXPIRES_AFTER
          value: $(params.image-expires-after)

        - name: ALWAYS_BUILD_INDEX
          value: $(params.build-image-index)

        - name: IMAGES
          value:
            - $(tasks.build-images.results.IMAGE_REF[*])

        - name: BUILDAH_FORMAT
          value: $(params.buildah-format)

      runAfter:
        - build-images

      taskRef:
        resolver: bundles
        params:
          - name: name
            value: build-image-index

          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-build-image-index:0.2@sha256:30989fa1f475bb8f6bda811b26bd4ddf7187288ed5815ce634ba399341852c75

          - name: kind
            value: task

    - name: deprecated-base-image-check
      params:
        - name: IMAGE_URL
          value: $(tasks.build-image-index.results.IMAGE_URL)

        - name: IMAGE_DIGEST
          value: $(tasks.build-image-index.results.IMAGE_DIGEST)

      runAfter:
        - build-image-index

      taskRef:
        resolver: bundles
        params:
          - name: name
            value: deprecated-image-check

          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-deprecated-image-check:0.5@sha256:e3a55ccdf1091b4a35507f9ee2d1918d8e89a5f96babcb5486b491226da03d6f

          - name: kind
            value: task

      when:
        - input: $(params.skip-checks)
          operator: in
          values:
            - "false"

    - name: clair-scan
      params:
        - name: image-digest
          value: $(tasks.build-image-index.results.IMAGE_DIGEST)

        - name: image-url
          value: $(tasks.build-image-index.results.IMAGE_URL)

      runAfter:
        - build-image-index

      taskRef:
        resolver: bundles
        params:
          - name: name
            value: clair-scan

          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-clair-scan:0.3@sha256:b01d8e2c58eb407ac23fa07b8e44c4631f0cf7257e87507c829fa2486aff9804

          - name: kind
            value: task
      when:
        - input: $(params.skip-checks)
          operator: in
          values:
            - "false"

    - name: ecosystem-cert-preflight-checks
      params:
        - name: image-url
          value: $(tasks.build-image-index.results.IMAGE_URL)

      runAfter:
        - build-image-index

      taskRef:
        resolver: bundles
        params:
          - name: name
            value: ecosystem-cert-preflight-checks

          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-ecosystem-cert-preflight-checks:0.2@sha256:40bc4bcc1c52c114139daee60ec2ddeb59921ecef8a68f241d5593c79b2a21d6

          - name: kind
            value: task
      when:
        - input: $(params.skip-checks)
          operator: in
          values:
            - "false"

    - name: sast-snyk-check
      params:
        - name: image-digest
          value: $(tasks.build-image-index.results.IMAGE_DIGEST)

        - name: image-url
          value: $(tasks.build-image-index.results.IMAGE_URL)

        - name: SOURCE_ARTIFACT
          value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)

        - name: CACHI2_ARTIFACT
          value: $(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)

        - name: ARGS
          value: "--project-name=linux-mcp-server --report --org=12d05a23-73a7-4a1d-9162-ab12e8c051c4"

      runAfter:
        - build-image-index

      taskRef:
        resolver: bundles
        params:
          - name: name
            value: sast-snyk-check-oci-ta

          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-sast-snyk-check-oci-ta:0.4@sha256:0c2ab8ce6d419400b63dd67d061052ac51de7b1ebe93f8ae86ed07ac638d756d

          - name: kind
            value: task

      when:
        - input: $(params.skip-checks)
          operator: in
          values:
            - "false"

    - name: clamav-scan
      params:
        - name: image-digest
          value: $(tasks.build-image-index.results.IMAGE_DIGEST)

        - name: image-url
          value: $(tasks.build-image-index.results.IMAGE_URL)

      runAfter:
        - build-image-index

      taskRef:
        resolver: bundles
        params:
          - name: name
            value: clamav-scan

          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-clamav-scan:0.3@sha256:5b5b31eae9063a00b91acc049b536e548d87c730068e439eefe33ab5238ee118

          - name: kind
            value: task

      when:
        - input: $(params.skip-checks)
          operator: in
          values:
            - "false"

    - name: coverity-availability-check
      runAfter:
        - build-image-index

      taskRef:
        resolver: bundles
        params:
          - name: name
            value: coverity-availability-check

          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-coverity-availability-check:0.2@sha256:a24d8f3cd01ccc54fa6fb73aa57a78f5559a0e58eddfe0583fc9cb97d59b4efc

          - name: kind
            value: task

      when:
        - input: $(params.skip-checks)
          operator: in
          values:
            - "false"

    - name: sast-coverity-check
      params:
        - name: image-digest
          value: $(tasks.build-image-index.results.IMAGE_DIGEST)

        - name: image-url
          value: $(tasks.build-image-index.results.IMAGE_URL)

        - name: IMAGE
          value: $(params.output-image)

        - name: DOCKERFILE
          value: $(params.dockerfile)

        - name: CONTEXT
          value: $(params.path-context)

        - name: HERMETIC
          value: $(params.hermetic)

        - name: PREFETCH_INPUT
          value: $(params.prefetch-input)

        - name: IMAGE_EXPIRES_AFTER
          value: $(params.image-expires-after)

        - name: COMMIT_SHA
          value: $(tasks.clone-repository.results.commit)

        - name: BUILD_ARGS
          value:
            - $(params.build-args[*])
            - SOURCE_DATE_EPOCH=$(tasks.clone-repository.results.commit-timestamp)

        - name: BUILD_ARGS_FILE
          value: $(params.build-args-file)

        - name: SOURCE_ARTIFACT
          value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)

        - name: CACHI2_ARTIFACT
          value: $(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)

      runAfter:
        - coverity-availability-check

      taskRef:
        resolver: bundles
        params:
          - name: name
            value: sast-coverity-check-oci-ta

          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-sast-coverity-check-oci-ta:0.3@sha256:e8c63570f1d01d70b2a21b22a2a4aad9ca7d5c0327d8b2a4058a6e616cce17ca

          - name: kind
            value: task

      when:
        - input: "true"
          operator: in
          values:
            - "false"

        - input: $(tasks.coverity-availability-check.results.STATUS)
          operator: in
          values:
            - success

    - name: sast-shell-check
      params:
        - name: image-digest
          value: $(tasks.build-image-index.results.IMAGE_DIGEST)

        - name: image-url
          value: $(tasks.build-image-index.results.IMAGE_URL)

        - name: SOURCE_ARTIFACT
          value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)

        - name: CACHI2_ARTIFACT
          value: $(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)

      runAfter:
        - build-image-index

      taskRef:
        resolver: bundles
        params:
          - name: name
            value: sast-shell-check-oci-ta

          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-sast-shell-check-oci-ta:0.1@sha256:f475b4b6b0c1687fa1aafa5ba38813e04f080b185af2975e12b457742d9dd857

          - name: kind
            value: task

      when:
        - input: $(params.skip-checks)
          operator: in
          values:
            - "false"

    - name: sast-unicode-check
      params:
        - name: image-digest
          value: $(tasks.build-image-index.results.IMAGE_DIGEST)

        - name: image-url
          value: $(tasks.build-image-index.results.IMAGE_URL)

        - name: SOURCE_ARTIFACT
          value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)

        - name: CACHI2_ARTIFACT
          value: $(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)

      runAfter:
        - build-image-index

      taskRef:
        resolver: bundles
        params:
          - name: name
            value: sast-unicode-check-oci-ta

          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-sast-unicode-check-oci-ta:0.4@sha256:b38140b2f0b2163def80e28a792b2702245d38a5610a504f2e56c198f3b8f70b

          - name: kind
            value: task

      when:
        - input: $(params.skip-checks)
          operator: in
          values:
            - "false"

    - name: apply-tags
      params:
        - name: IMAGE_URL
          value: $(tasks.build-image-index.results.IMAGE_URL)

        - name: IMAGE_DIGEST
          value: $(tasks.build-image-index.results.IMAGE_DIGEST)

        - name: ADDITIONAL_TAGS
          value:
            - $(params.additional-tags[*])
            - $(params.tag-prefix)$(tasks.clone-repository.results.short-commit)

      runAfter:
        - build-image-index

      taskRef:
        resolver: bundles
        params:
          - name: name
            value: apply-tags

          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-apply-tags:0.3@sha256:510b6d2a3b188adeb716e49566b57d611ab36bd69a2794b5ddfc11dbf014c2ca

          - name: kind
            value: task

    - name: push-dockerfile
      params:
        - name: IMAGE
          value: $(tasks.build-image-index.results.IMAGE_URL)

        - name: IMAGE_DIGEST
          value: $(tasks.build-image-index.results.IMAGE_DIGEST)

        - name: DOCKERFILE
          value: $(params.dockerfile)

        - name: CONTEXT
          value: $(params.path-context)

        - name: SOURCE_ARTIFACT
          value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)

      runAfter:
        - build-image-index

      taskRef:
        resolver: bundles
        params:
          - name: name
            value: push-dockerfile-oci-ta

          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-push-dockerfile-oci-ta:0.1@sha256:2623be4a9bad87ade614b4b24a8f98a4e100042a845e8f162b8237168697294c

          - name: kind
            value: task

    - name: rpms-signature-scan
      params:
        - name: image-digest
          value: $(tasks.build-image-index.results.IMAGE_DIGEST)

        - name: image-url
          value: $(tasks.build-image-index.results.IMAGE_URL)

      runAfter:
        - build-image-index

      taskRef:
        resolver: bundles
        params:
          - name: name
            value: rpms-signature-scan

          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-rpms-signature-scan:0.2@sha256:23f133f47d13e6fd35ad6a65138f5b48bd2e6c4e66a2512991ff9f7d90cd7e0e

          - name: kind
            value: task
