apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: verify-container-lifecycle
  namespace: rhel-lightspeed-tenant
spec:
  description: Verifies that the MCP server container starts, has correct user permissions, and responds to JSON-RPC.
  params:
    - name: image_url
      description: The URL of the image to verify.
      type: string

    - name: startup_timeout
      description: Time to wait for server statup
      type: string
      default: "30s"
  steps:
    - name: verify-user-and-startup
      image: $(params.image_url)
      workingDir: $(workspaces.source.path)
      script: |
        ./scripts/verify_container_lifecycle.sh

    - name: verify-mcp-handshake
      image: $(params.image_url)
      workingDir: $(workspaces.source.path)
      script: |
        ./scripts/verify_mcp_handshake.sh
