apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: mcp-protocol-audit
spec:
  description: Audits the MCP server for protocol compliance, tool discovery, and stdout hygiene.
  params:
    - name: image_url
      type: string
      description: The URL of the image to audit.
  steps:
    - name: validate-tool-discovery
      image: $(params.image_url)
      workingDir: $(workspaces.source.path)
      script: |
        ./scripts/mcp_protocol_audit.sh

    - name: verify-stdout-hygiene
      image: $(params.image_url)
      workingDir: $(workspaces.source.path)
      script: |
        ./scripts/verify_stdout_hygiene.sh
