# Disable debuginfo/debugsource generation. Vendored pydantic_core ships
# prebuilt .so files that lack debug sources, causing empty debugsourcefiles.list.
%global debug_package %{nil}
%define python_package_src linux_mcp_server

Name:           linux-mcp-server
Version:        0.1.0a3
Release:        1%{?dist}
Summary:        MCP server for read-only Linux system administration

License:        Apache-2.0 AND GPL-3.0-or-later
URL:            https://github.com/rhel-lightspeed/linux-mcp-server
Source:         %{url}/archive/v%{version}/linux-mcp-server-%{version}.tar.gz
# Vendored dependency wheels generated by pip download from requirements.txt.
# Contains wheels for all target Python versions (cp39, cp312) and x86_64.
# Shipped as a GitHub release artifact for tagged releases; generated by packit
# post-upstream-clone action for PR/main builds.
Source1:        %{url}/releases/download/v%{version}/vendor-wheels.tar.gz

# Not BuildArch: noarch because pydantic_core contains compiled .so files

# Build dependencies
BuildRequires:  python3-devel
BuildRequires:  python3-pip
BuildRequires:  python3-setuptools
BuildRequires:  python3-wheel

# Not needed after RHEL 10 as it is native in Python 3.11+
%if 0%{?rhel} && 0%{?rhel} < 10
BuildRequires:  python3-tomli
Requires:       python3-tomli
%endif

%global _description %{expand:
MCP server for read-only Linux system administration, diagnostics, and troubleshooting.}

# All Python dependencies are vendored in _vendor. Suppress the auto-generated
# python3.Xdist(...) Requires so RPM does not demand them as system packages.
%{?python_disable_dependency_generator}

%description %_description


%prep
%autosetup -p1

# Remove pytest options not available in RHEL
sed -i '/^addopts = \[/,/^\]/d' pyproject.toml
sed -i '/^asyncio_mode = /d' pyproject.toml

# Remove license-files as this is a conflicting property with older setuptools
sed -i '/^license-files = /d' pyproject.toml

# Switch build backend from hatchling to setuptools (hatchling not available on RHEL)
sed -i 's/requires = \["hatchling", "hatch-vcs"\]/requires = ["setuptools", "wheel"]/' pyproject.toml
sed -i 's/build-backend = "hatchling.build"/build-backend = "setuptools.build_meta"/' pyproject.toml

# Remove dynamic version (set by hatch-vcs) and set static version
sed -i '/^dynamic = \["version"\]/d' pyproject.toml
sed -i '/^name = "linux-mcp-server"/a version = "%{version}"' pyproject.toml

# Add setuptools package discovery and include .so from vendored deps
cat >> pyproject.toml <<'EOF'

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"*" = ["*.so"]
EOF

# Install vendored dependency wheels into the _vendor directory so they are
# included in the wheel built during %%build. The tarball contains wheels for
# multiple Python versions (cp39, cp312). A per-version requirements file
# selects the correct packages and pip picks the compatible wheel.
tar xzf %{SOURCE1}
%{python3} -m pip install --no-deps --no-index \
    --find-links vendor_wheels --target src/%{python_package_src}/_vendor \
    -r vendor_wheels/requirements-%{python3_version_nodots}.txt

%build
%py3_build_wheel

%install
%py3_install_wheel %{python_package_src}-%{version}-py3-none-any.whl

%files
%license LICENSE licenses/GPL-3.0.txt
%doc README.md

%{_bindir}/linux-mcp-server
%{python3_sitelib}/%{python_package_src}/
%{python3_sitelib}/%{python_package_src}-%{version}.dist-info/

%changelog
%autochangelog
