apiVersion: v1
kind: ServiceAccount
metadata:
  name: linux-mcp-server
  namespace: rhel-mcp
  labels:
    app: linux-mcp-server
    app.kubernetes.io/name: linux-mcp-server
    app.kubernetes.io/component: server
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: linux-mcp-server
  namespace: rhel-mcp
  labels:
    app: linux-mcp-server
rules:
# Add any specific permissions if needed
# Currently, the server doesn't need any Kubernetes API access
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: linux-mcp-server
  namespace: rhel-mcp
  labels:
    app: linux-mcp-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: linux-mcp-server
subjects:
- kind: ServiceAccount
  name: linux-mcp-server
  namespace: rhel-mcp

