name: CI
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


env:
  PIP_DISABLE_PIP_VERSION_CHECK: 1
  COVERAGE_IGOR_VERBOSE: 1
  FORCE_COLOR: 1    # Get colored pytest output


jobs:
  sanity:
    name: Sanity - ${{ matrix.test.name }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        test:
          - name: Type
            step_name: Check types
            command: pyright

          - name: Lint
            step_name: Run lint
            command: ruff check --diff

          - name: Format
            step_name: Run format check
            command: ruff format --diff

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Install Python
        uses: actions/setup-python@v6.0.0
        with:
          python-version-file: pyproject.toml

      - name: Install uv
        uses: astral-sh/setup-uv@v7.1.0
        with:
          enable-cache: true
          prune-cache: false

      - name: Install dependencies
        run: uv sync --locked --group lint

      - name: "Show environment"
        run: |
          python -VV
          python -m site
          uv --version
          env | sort
          ls -ld $(python -c "import site; print(site.getsitepackages()[0])")
          whoami

      - name: ${{ matrix.test.step_name }}
        run: uv run --locked ${{ matrix.test.command }}

  tests:
    name: Unit - ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.13t"
          - "3.14"
          - "3.14t"

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Install Python
        uses: actions/setup-python@v6.0.0
        with:
          python-version-file: pyproject.toml

      - name: Install uv
        uses: astral-sh/setup-uv@v7.1.0
        with:
          enable-cache: true
          prune-cache: false

      - name: Install dependencies
        run: uv sync --locked --group test

      - name: Show environment
        run: |
          set -x
          python -VV
          python -m site
          uv --version
          ls -ld $(python -c "import site; print(site.getsitepackages()[0])")
          whoami

      - name: Run tests
        run: uv run --locked pytest --cov-report=xml

      - name: Upload coverage report
        uses: codecov/codecov-action@v5.5.1
        with:
          env_vars: OS,PYTHON
          disable_search: true
          files: coverage/coverage.xml
          fail_ci_if_error: true
          flags: unittests
